### ISSUE TITLE
Getting Radio Value

### ISSUE THREAD

**Issue by baidoct** [milesj/formation#1]
Hi there,

Great project, however, when I'm trying to get the value with the GET $form->get function of an Radio Type Input, it doesn't return anything. 

Example:

```
$form->radio('gender', array('value' => 'male', 'default' => true));
$gender = $form->get('gender');
echo $gender;
```

Any way to fix this issue?
Thanks!

**Comment by milesj** [comment]
The `get()` method should only be used after `process()` is called, as it uses `$_POST`.
